In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
f1=pd.read_csv("fund_allocations.csv")
f2=pd.read_csv("fund_config.csv")
f3=pd.read_csv("fund_ratios.csv")
f4=pd.read_csv("fund_specs.csv")
f5=pd.read_csv("other_specs.csv")
f6=pd.read_csv("return_3year.csv")
f7=pd.read_csv("return_5year.csv")
f8=pd.read_csv("return_10year.csv")
f9=pd.read_csv("bond_ratings.csv")
f10=pd.read_csv("sample_submission.csv")

f1

,portfolio_communication_allocation,portfolio_financial_services,portfolio_industrials_allocation,portfolio_tech_allocation,portfolio_materials_basic_allocation,portfolio_energy_allocation,portfolio_consumer_defence_allocation,portfolio_healthcare_allocation,portfolio_property_allocation,id,portfolio_utils_allocation,portfolio_cyclical_consumer_allocation
0,0.00,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,67922,0.00,0.00
1,0.78,9.77,9.97,35.51,2.86,0.38,5.88,14.41,2.67,134783,0.39,17.38
2,4.70,16.40,11.45,25.09,8.36,0.00,9.42,16.47,1.03,61271,0.00,7.09
3,6.53,13.80,10.91,0.16,2.22,6.79,25.73,9.00,0.00,64412,19.42,5.43
4,3.49,13.95,10.51,19.26,3.75,5.11,7.29,12.22,10.41,184058,3.07,10.95
...,...,...,...,...,...,...,...,...,...,...,...,...
24995,6.53,21.00,7.42,10.67,3.00,9.73,7.12,13.92,4.59,142001,7.06,8.96
24996,3.70,18.83,10.10,19.32,3.40,5.80,8.83,10.97,4.75,40598,2.40,11.90
24997,1.17,8.71,14.03,6.89,5.52,8.91,2.49,4.84,28.24,202562,12.64,6.56
24998,2.21,19.92,12.55,14.62,0.00,0.00,3.27,25.31,0.00,144818,0.00,22.12
24999,0.04,20.62,15.29,19.87,7.78,2.97,8.60,10.80,0.00,219275,0.00,14.05

In [44]:
ini_test=f3[f3.fund_id.isin(f10.fund_id)==True]

In [45]:
ini_test

,fund_id,tag,fund_ratio_net_annual_expense,pb_ratio,ps_ratio,mmc,pc_ratio,pe_ratio
0,264614c6-5ac3-4146-ba26-1674b136cb40,67922,1.44,1.71,1.31,"19,857.41",5.91,14.51
7,08702e4f-c5bb-4f0a-b63b-f9e4a0eb2425,138257,1.04,2.18,1.17,"38,651.17",5.87,13.16
16,cf56db43-046b-49d0-b8f0-90fe9cf8aacf,191978,0.85,2.28,1.34,"3,107.63",8.63,18.05
24,3faa81fc-9640-43d0-8b68-e5b06c65bfe6,105506,0.27,2.03,1.28,"29,145.49",6.96,13.37
28,09e24f3d-7191-4207-887c-98f31c6b59d2,58517,0.36,0.00,0.0,0,0,0
...,...,...,...,...,...,...,...,...
24983,fc278788-24bf-4844-a538-d8c67d47275c,197765,1.30,2.26,1.68,"47,733.5",9.28,16.68
24992,0a3c101f-c969-4e85-8395-3dc3e33dd3d6,139247,0.71,1.83,1.27,"68,651.59",6.41,13.62
24996,12fc8949-6563-4dd4-a7cc-0400131fa6ab,40598,1.02,1.94,1.36,"37,550.75",7.61,14.3
24998,65421547-1407-4c50-92dc-e1cb1e9972dd,144818,1.10,0.98,0.86,"14,859.2",3.8,7.89
24999,e0284aeb-630a-4499-8745-2a9abba49528,219275,1.97,2.38,1.63,"35,795.28",11.55,17.8

In [6]:
f3f4= pd.merge(f4,f3,on='tag',how='left')

In [7]:
f3f4

,investment_class,currency,total_assets,yield,greatstone_rating,inception_date,tag,fund_size,return_ytd,fund_id,fund_ratio_net_annual_expense,pb_ratio,ps_ratio,mmc,pc_ratio,pe_ratio
0,Value,USD,1.185000e+07,5.57,NaN,2015-02-02,67922,Large,20.19,264614c6-5ac3-4146-ba26-1674b136cb40,1.44,1.71,1.31,"19,857.41",5.91,14.51
1,Growth,USD,1.397000e+10,0.42,3.0,2012-05-30,134783,Large,16.79,f5ad58c2-fdea-4087-8678-e04744f89f90,0.58,5.30,3.38,"72,347.03",15.95,18.88
2,Growth,USD,2.660000e+09,0.02,4.0,1987-08-23,61271,Large,17.13,3c13f4ab-02c4-4ca7-a133-7e996ec5d0c4,0.99,5.40,3.67,"68,857.43",15.97,23.27
3,Value,USD,1.957000e+10,2.71,3.0,2005-10-24,64412,Large,11.63,ff78bdd8-59eb-4cef-9f3c-b1baacce9554,0.52,2.23,1.63,"43,266.62",8.93,12.7
4,Blend,USD,2.847000e+07,2.44,0.0,2016-12-12,184058,Large,10.25,63d8406d-c525-494a-8e03-d4fc4cfcb571,0.75,2.02,1.4,"43,747.9",7.59,14.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Value,USD,9.418100e+08,1.80,1.0,1986-12-29,142001,Large,10.31,c3d73c76-6b0c-4ee4-b562-e9bff53e4c8c,1.12,1.78,1.11,"45,619.69",8.64,11.3
24996,Blend,USD,7.090800e+08,1.03,NaN,2003-09-01,40598,Large,11.88,12fc8949-6563-4dd4-a7cc-0400131fa6ab,1.02,1.94,1.36,"37,550.75",7.61,14.3
24997,Blend,USD,8.778000e+07,5.08,1.0,2014-11-30,202562,Medium,7.29,7fe4b63a-c42e-4c2b-a59b-d29ade57ecfd,0.95,1.52,1.5,"7,378.47",4.63,14.49
24998,Value,USD,1.520000e+09,0.00,NaN,2000-06-25,144818,Medium,13.74,65421547-1407-4c50-92dc-e1cb1e9972dd,1.10,0.98,0.86,"14,859.2",3.8,7.89
24999,Growth,USD,5.387100e+08,0.22,NaN,2001-06-17,219275,Large,14.81,e0284aeb-630a-4499-8745-2a9abba49528,1.97,2.38,1.63,"35,795.28",11.55,17.8

In [8]:
f3f4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25000 entries, 0 to 24999
Data columns (total 16 columns):
investment_class                 23520 non-null object
currency                         25000 non-null object
total_assets                     24881 non-null float64
yield                            24873 non-null float64
greatstone_rating                20000 non-null float64
inception_date                   25000 non-null object
tag                              25000 non-null int64
fund_size                        23520 non-null object
return_ytd                       24892 non-null float64
fund_id                          25000 non-null object
fund_ratio_net_annual_expense    25000 non-null float64
pb_ratio                         24886 non-null float64
ps_ratio                         24886 non-null object
mmc                              24886 non-null object
pc_ratio                         24886 non-null object
pe_ratio                         24886 non-null object
dtypes: float64(6), int64(1), object(9)
memory usage: 3.2+ MB

In [12]:
f3f4.columns

Index(['investment_class', 'currency', 'total_assets', 'yield',
       'greatstone_rating', 'inception_date', 'tag', 'fund_size', 'return_ytd',
       'fund_id', 'fund_ratio_net_annual_expense', 'pb_ratio', 'ps_ratio',
       'mmc', 'pc_ratio', 'pe_ratio'],
      dtype='object')

In [23]:
f1=f1.rename(columns={'id':'tag'})

In [24]:
f1

,portfolio_communication_allocation,portfolio_financial_services,portfolio_industrials_allocation,portfolio_tech_allocation,portfolio_materials_basic_allocation,portfolio_energy_allocation,portfolio_consumer_defence_allocation,portfolio_healthcare_allocation,portfolio_property_allocation,tag,portfolio_utils_allocation,portfolio_cyclical_consumer_allocation
0,0.00,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,67922,0.00,0.00
1,0.78,9.77,9.97,35.51,2.86,0.38,5.88,14.41,2.67,134783,0.39,17.38
2,4.70,16.40,11.45,25.09,8.36,0.00,9.42,16.47,1.03,61271,0.00,7.09
3,6.53,13.80,10.91,0.16,2.22,6.79,25.73,9.00,0.00,64412,19.42,5.43
4,3.49,13.95,10.51,19.26,3.75,5.11,7.29,12.22,10.41,184058,3.07,10.95
...,...,...,...,...,...,...,...,...,...,...,...,...
24995,6.53,21.00,7.42,10.67,3.00,9.73,7.12,13.92,4.59,142001,7.06,8.96
24996,3.70,18.83,10.10,19.32,3.40,5.80,8.83,10.97,4.75,40598,2.40,11.90
24997,1.17,8.71,14.03,6.89,5.52,8.91,2.49,4.84,28.24,202562,12.64,6.56
24998,2.21,19.92,12.55,14.62,0.00,0.00,3.27,25.31,0.00,144818,0.00,22.12
24999,0.04,20.62,15.29,19.87,7.78,2.97,8.60,10.80,0.00,219275,0.00,14.05

In [25]:
f1f3f4=pd.merge(f3f4,f1,on='tag',how='left')

In [26]:
f1f3f4

,investment_class,currency,total_assets,yield,greatstone_rating,inception_date,tag,fund_size,return_ytd,fund_id,...,portfolio_financial_services,portfolio_industrials_allocation,portfolio_tech_allocation,portfolio_materials_basic_allocation,portfolio_energy_allocation,portfolio_consumer_defence_allocation,portfolio_healthcare_allocation,portfolio_property_allocation,portfolio_utils_allocation,portfolio_cyclical_consumer_allocation
0,Value,USD,1.185000e+07,5.57,NaN,2015-02-02,67922,Large,20.19,264614c6-5ac3-4146-ba26-1674b136cb40,...,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00
1,Growth,USD,1.397000e+10,0.42,3.0,2012-05-30,134783,Large,16.79,f5ad58c2-fdea-4087-8678-e04744f89f90,...,9.77,9.97,35.51,2.86,0.38,5.88,14.41,2.67,0.39,17.38
2,Growth,USD,2.660000e+09,0.02,4.0,1987-08-23,61271,Large,17.13,3c13f4ab-02c4-4ca7-a133-7e996ec5d0c4,...,16.40,11.45,25.09,8.36,0.00,9.42,16.47,1.03,0.00,7.09
3,Value,USD,1.957000e+10,2.71,3.0,2005-10-24,64412,Large,11.63,ff78bdd8-59eb-4cef-9f3c-b1baacce9554,...,13.80,10.91,0.16,2.22,6.79,25.73,9.00,0.00,19.42,5.43
4,Blend,USD,2.847000e+07,2.44,0.0,2016-12-12,184058,Large,10.25,63d8406d-c525-494a-8e03-d4fc4cfcb571,...,13.95,10.51,19.26,3.75,5.11,7.29,12.22,10.41,3.07,10.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Value,USD,9.418100e+08,1.80,1.0,1986-12-29,142001,Large,10.31,c3d73c76-6b0c-4ee4-b562-e9bff53e4c8c,...,21.00,7.42,10.67,3.00,9.73,7.12,13.92,4.59,7.06,8.96
24996,Blend,USD,7.090800e+08,1.03,NaN,2003-09-01,40598,Large,11.88,12fc8949-6563-4dd4-a7cc-0400131fa6ab,...,18.83,10.10,19.32,3.40,5.80,8.83,10.97,4.75,2.40,11.90
24997,Blend,USD,8.778000e+07,5.08,1.0,2014-11-30,202562,Medium,7.29,7fe4b63a-c42e-4c2b-a59b-d29ade57ecfd,...,8.71,14.03,6.89,5.52,8.91,2.49,4.84,28.24,12.64,6.56
24998,Value,USD,1.520000e+09,0.00,NaN,2000-06-25,144818,Medium,13.74,65421547-1407-4c50-92dc-e1cb1e9972dd,...,19.92,12.55,14.62,0.00,0.00,3.27,25.31,0.00,0.00,22.12
24999,Growth,USD,5.387100e+08,0.22,NaN,2001-06-17,219275,Large,14.81,e0284aeb-630a-4499-8745-2a9abba49528,...,20.62,15.29,19.87,7.78,2.97,8.60,10.80,0.00,0.00,14.05

In [27]:
f1f2f3f4= pd.merge(f1f3f4,f2, on='fund_id')

In [28]:
f1f2f3f4

,investment_class,currency,total_assets,yield,greatstone_rating,inception_date,tag,fund_size,return_ytd,fund_id,...,portfolio_materials_basic_allocation,portfolio_energy_allocation,portfolio_consumer_defence_allocation,portfolio_healthcare_allocation,portfolio_property_allocation,portfolio_utils_allocation,portfolio_cyclical_consumer_allocation,category,parent_company,fund_name
0,Value,USD,1.185000e+07,5.57,NaN,2015-02-02,67922,Large,20.19,264614c6-5ac3-4146-ba26-1674b136cb40,...,0.00,100.00,0.00,0.00,0.00,0.00,0.00,Energy Limited Partnership,DWS,DWS RREEF MLP & Energy Infrastructure Fund - C...
1,Growth,USD,1.397000e+10,0.42,3.0,2012-05-30,134783,Large,16.79,f5ad58c2-fdea-4087-8678-e04744f89f90,...,2.86,0.38,5.88,14.41,2.67,0.39,17.38,Large Growth,Janus Henderson,Janus Henderson Research Fund Class N
2,Growth,USD,2.660000e+09,0.02,4.0,1987-08-23,61271,Large,17.13,3c13f4ab-02c4-4ca7-a133-7e996ec5d0c4,...,8.36,0.00,9.42,16.47,1.03,0.00,7.09,Large Growth,Calvert Research and Management,Calvert Equity Fund Class A
3,Value,USD,1.957000e+10,2.71,3.0,2005-10-24,64412,Large,11.63,ff78bdd8-59eb-4cef-9f3c-b1baacce9554,...,2.22,6.79,25.73,9.00,0.00,19.42,5.43,Large Value,Invesco,Invesco Diversified Dividend Fund R5 Class
4,Blend,USD,2.847000e+07,2.44,0.0,2016-12-12,184058,Large,10.25,63d8406d-c525-494a-8e03-d4fc4cfcb571,...,3.75,5.11,7.29,12.22,10.41,3.07,10.95,Target-Date 2035,PGIM Funds (Prudential),Prudential Day One 2035 Fund Class R3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Value,USD,9.418100e+08,1.80,1.0,1986-12-29,142001,Large,10.31,c3d73c76-6b0c-4ee4-b562-e9bff53e4c8c,...,3.00,9.73,7.12,13.92,4.59,7.06,8.96,Large Value,Federated,"Federated Equity Income Fund, Inc. Class A Shares"
24996,Blend,USD,7.090800e+08,1.03,NaN,2003-09-01,40598,Large,11.88,12fc8949-6563-4dd4-a7cc-0400131fa6ab,...,3.40,5.80,8.83,10.97,4.75,2.40,11.90,World Large Stock,AllianceBernstein,AB Tax-Managed Wealth Appreciation Strategy Cl...
24997,Blend,USD,8.778000e+07,5.08,1.0,2014-11-30,202562,Medium,7.29,7fe4b63a-c42e-4c2b-a59b-d29ade57ecfd,...,5.52,8.91,2.49,4.84,28.24,12.64,6.56,Allocation - 30% to 50% Equity,OppenheimerFunds,Oppenheimer Global Multi-Asset Income Fund Cla...
24998,Value,USD,1.520000e+09,0.00,NaN,2000-06-25,144818,Medium,13.74,65421547-1407-4c50-92dc-e1cb1e9972dd,...,0.00,0.00,3.27,25.31,0.00,0.00,22.12,Mid-Cap Blend,Miller Value Funds,Miller Opportunity Trust Class I
24999,Growth,USD,5.387100e+08,0.22,NaN,2001-06-17,219275,Large,14.81,e0284aeb-630a-4499-8745-2a9abba49528,...,7.78,2.97,8.60,10.80,0.00,0.00,14.05,Foreign Large Growth,DWS,DWS International Growth Fund - Class C

In [29]:
f1f2f3f4f5=pd.merge(f1f2f3f4,f5,on='tag')

In [30]:
f1f2f3f4f5

,investment_class,currency,total_assets,yield,greatstone_rating_x,inception_date,tag,fund_size,return_ytd,fund_id,...,2018_return_fund,2017_return_fund,greatstone_rating_y,category_ratio_net_annual_expense,category_return_2015,1_month_fund_return,bond_percentage_of_porfolio,portfolio_preferred,2010_return_category,2013_category_return
0,Value,USD,1.185000e+07,5.57,NaN,2015-02-02,67922,Large,20.19,264614c6-5ac3-4146-ba26-1674b136cb40,...,-12.23,-3.31,NaN,1.75,-34.98,4.12,0.00,0.00,NaN,NaN
1,Growth,USD,1.397000e+10,0.42,3.0,2012-05-30,134783,Large,16.79,f5ad58c2-fdea-4087-8678-e04744f89f90,...,-2.62,26.39,3.0,1.06,3.60,2.33,0.00,0.00,NaN,33.92
2,Growth,USD,2.660000e+09,0.02,4.0,1987-08-23,61271,Large,17.13,3c13f4ab-02c4-4ca7-a133-7e996ec5d0c4,...,5.04,25.79,4.0,1.06,3.60,3.77,0.58,0.08,15.53,33.92
3,Value,USD,1.957000e+10,2.71,3.0,2005-10-24,64412,Large,11.63,ff78bdd8-59eb-4cef-9f3c-b1baacce9554,...,-7.54,8.53,3.0,1.00,-4.05,1.46,0.00,0.00,13.66,31.21
4,Blend,USD,2.847000e+07,2.44,0.0,2016-12-12,184058,Large,10.25,63d8406d-c525-494a-8e03-d4fc4cfcb571,...,-7.37,17.52,0.0,0.45,NaN,1.28,24.97,0.02,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Value,USD,9.418100e+08,1.80,1.0,1986-12-29,142001,Large,10.31,c3d73c76-6b0c-4ee4-b562-e9bff53e4c8c,...,-11.69,16.06,1.0,1.00,-4.05,-0.22,4.01,0.00,13.66,31.21
24996,Blend,USD,7.090800e+08,1.03,NaN,2003-09-01,40598,Large,11.88,12fc8949-6563-4dd4-a7cc-0400131fa6ab,...,-9.89,22.78,NaN,1.11,-1.69,0.85,0.00,0.00,13.74,25.19
24997,Blend,USD,8.778000e+07,5.08,1.0,2014-11-30,202562,Medium,7.29,7fe4b63a-c42e-4c2b-a59b-d29ade57ecfd,...,-7.61,6.29,1.0,0.79,-2.32,1.23,43.11,4.29,NaN,NaN
24998,Value,USD,1.520000e+09,0.00,NaN,2000-06-25,144818,Medium,13.74,65421547-1407-4c50-92dc-e1cb1e9972dd,...,-9.53,26.21,NaN,1.06,-4.75,-4.96,0.00,0.00,22.52,34.10
24999,Growth,USD,5.387100e+08,0.22,NaN,2001-06-17,219275,Large,14.81,e0284aeb-630a-4499-8745-2a9abba49528,...,-17.70,24.18,NaN,1.13,0.95,1.75,0.00,1.60,14.78,18.58

In [50]:
f1_6=pd.merge(f1f2f3f4f5,f6,on='tag')
f1_6

,investment_class,currency,total_assets,yield,greatstone_rating_x,inception_date,tag,fund_size,return_ytd,fund_id,...,fund_beta_3years,3years_fund_r_squared,3years_fund_std,category_beta_3years,fund_return_3years_y,3_years_alpha_category,3_years_return_mean_annual_category,3yrs_sharpe_ratio_category,3years_category_r_squared,3_years_return_category
0,Value,USD,1.185000e+07,5.57,NaN,2015-02-02,67922,Large,20.19,264614c6-5ac3-4146-ba26-1674b136cb40,...,1.20,54.83,16.25,0.01,4.24,-0.04,0.01,0.00,0.42,7.36
1,Growth,USD,1.397000e+10,0.42,3.0,2012-05-30,134783,Large,16.79,f5ad58c2-fdea-4087-8678-e04744f89f90,...,1.07,88.46,12.26,0.01,14.39,0.01,0.01,0.01,0.84,15.35
2,Growth,USD,2.660000e+09,0.02,4.0,1987-08-23,61271,Large,17.13,3c13f4ab-02c4-4ca7-a133-7e996ec5d0c4,...,0.85,84.41,9.93,0.01,16.42,0.01,0.01,0.01,0.84,15.35
3,Value,USD,1.957000e+10,2.71,3.0,2005-10-24,64412,Large,11.63,ff78bdd8-59eb-4cef-9f3c-b1baacce9554,...,0.70,81.02,8.36,0.01,6.85,-0.02,0.01,0.01,0.84,10.01
4,Blend,USD,2.847000e+07,2.44,0.0,2016-12-12,184058,Large,10.25,63d8406d-c525-494a-8e03-d4fc4cfcb571,...,NaN,NaN,NaN,0.01,0.00,-0.01,0.01,0.01,0.97,9.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Value,USD,9.418100e+08,1.80,1.0,1986-12-29,142001,Large,10.31,c3d73c76-6b0c-4ee4-b562-e9bff53e4c8c,...,0.96,88.78,10.88,0.01,8.23,-0.02,0.01,0.01,0.84,10.01
24996,Blend,USD,7.090800e+08,1.03,NaN,2003-09-01,40598,Large,11.88,12fc8949-6563-4dd4-a7cc-0400131fa6ab,...,0.81,77.22,9.74,0.01,9.39,0.03,0.01,0.01,0.73,9.96
24997,Blend,USD,8.778000e+07,5.08,1.0,2014-11-30,202562,Medium,7.29,7fe4b63a-c42e-4c2b-a59b-d29ade57ecfd,...,0.89,84.14,5.89,0.01,4.00,-0.01,0.00,0.01,0.88,5.53
24998,Value,USD,1.520000e+09,0.00,NaN,2000-06-25,144818,Medium,13.74,65421547-1407-4c50-92dc-e1cb1e9972dd,...,1.77,66.78,23.32,0.01,13.55,-0.04,0.01,0.01,0.81,9.67
24999,Growth,USD,5.387100e+08,0.22,NaN,2001-06-17,219275,Large,14.81,e0284aeb-630a-4499-8745-2a9abba49528,...,1.02,82.98,11.81,0.01,5.54,0.00,0.01,0.01,0.81,8.05

In [51]:
f1_8=pd.merge(f1_6,f8,on='fund_id')

In [52]:
f1_8

,investment_class,currency,total_assets,yield,greatstone_rating_x,inception_date,tag,fund_size,return_ytd,fund_id,...,10_years_beta_fund,10yrs_treynor_ratio_fund,10_years_return_mean_annual_category,10yrs_treynor_ratio_category,10_years_return_fund,10_years_alpha_category,10_years_beta_category,10years_category_std,10_years_return_mean_annual_fund,10_years_return_category
0,Value,USD,1.185000e+07,5.57,NaN,2015-02-02,67922,Large,20.19,264614c6-5ac3-4146-ba26-1674b136cb40,...,NaN,NaN,0.01,0.21,0.00,0.06,0.01,0.13,NaN,14.30
1,Growth,USD,1.397000e+10,0.42,3.0,2012-05-30,134783,Large,16.79,f5ad58c2-fdea-4087-8678-e04744f89f90,...,1.08,15.57,0.01,0.15,17.25,-0.01,0.01,0.14,1.42,15.94
2,Growth,USD,2.660000e+09,0.02,4.0,1987-08-23,61271,Large,17.13,3c13f4ab-02c4-4ca7-a133-7e996ec5d0c4,...,0.95,16.58,0.01,0.15,16.21,-0.01,0.01,0.14,1.33,15.94
3,Value,USD,1.957000e+10,2.71,3.0,2005-10-24,64412,Large,11.63,ff78bdd8-59eb-4cef-9f3c-b1baacce9554,...,0.84,16.38,0.01,0.14,14.12,-0.02,0.01,0.13,1.16,13.68
4,Blend,USD,2.847000e+07,2.44,0.0,2016-12-12,184058,Large,10.25,63d8406d-c525-494a-8e03-d4fc4cfcb571,...,NaN,NaN,0.01,0.08,0.00,-0.02,0.01,0.12,NaN,11.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Value,USD,9.418100e+08,1.80,1.0,1986-12-29,142001,Large,10.31,c3d73c76-6b0c-4ee4-b562-e9bff53e4c8c,...,0.92,11.7,0.01,0.14,11.16,-0.02,0.01,0.13,0.95,13.68
24996,Blend,USD,7.090800e+08,1.03,NaN,2003-09-01,40598,Large,11.88,12fc8949-6563-4dd4-a7cc-0400131fa6ab,...,0.82,12.87,0.01,0.14,10.99,0.04,0.01,0.14,0.95,11.79
24997,Blend,USD,8.778000e+07,5.08,1.0,2014-11-30,202562,Medium,7.29,7fe4b63a-c42e-4c2b-a59b-d29ade57ecfd,...,NaN,NaN,0.01,0.10,0.00,0.00,0.01,0.07,NaN,7.87
24998,Value,USD,1.520000e+09,0.00,NaN,2000-06-25,144818,Medium,13.74,65421547-1407-4c50-92dc-e1cb1e9972dd,...,1.67,10.86,0.01,0.13,18.64,-0.03,0.01,0.15,1.69,14.51
24999,Growth,USD,5.387100e+08,0.22,NaN,2001-06-17,219275,Large,14.81,e0284aeb-630a-4499-8745-2a9abba49528,...,0.92,9.42,0.01,0.10,9.09,0.02,0.01,0.15,0.83,9.97

<h3>preparing test data</h3>

In [63]:
test_data=f1_8[f1_8.fund_id.isin(f10.fund_id)]

In [73]:
for columns in test_data.columns[:-1]:
    q1 = test_data[columns].quantile(0.25)
    q3 = test_data[columns].quantile(0.75)
    iqr = q3 - q1
    
    low = q1-1.5*iqr
    high = q3+1.5*iqr
    test_data.loc[(test_data[columns] < low) | (test_data[columns] > high), columns] = test_data[columns].median()

TypeError: can't multiply sequence by non-int of type 'float'

In [64]:
train_data=f1_8[~f1_8.fund_id.isin(f10.fund_id)]

In [71]:
train_data[train_data.fund_id.isin(test_data.fund_id)==True].count()

investment_class                    0
currency                            0
total_assets                        0
yield                               0
greatstone_rating_x                 0
                                   ..
10_years_alpha_category             0
10_years_beta_category              0
10years_category_std                0
10_years_return_mean_annual_fund    0
10_years_return_category            0
Length: 104, dtype: int64